### PR TITLE
Use base class SplFileInfo instead of SplFileObject

### PR DESCRIPTION
**Pull request by Maxsh**
Using base class SplFileInfo for creating Storage to decrease dependency only for required methods. 
It allows also using Symfony Finder component easier.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Hi @Maxsh, thanks a lot for your contribution! 🎉

**Review by andrii-bodnar — APPROVED** [review]

**Comment by Maxsh** [comment]
Hi @andrii-bodnar thanks for the quick response! What the tag should I expect for a new version? 1.7.1 or 1.8.0

**Comment by andrii-bodnar** [comment]
@Maxsh 1.7.1

I will release this version in a few minutes

**Comment by Maxsh** [comment]
Great, thanks!

**Comment by andrii-bodnar** [comment]
@Maxsh done ✅ 

Thanks again for your contribution!

**Pull request merged**
