### PR TITLE
feat: Add Strings Exporter Settings API #147

### PR DESCRIPTION
**Pull request by faizan1191**
This pull request will add Crowdin Strings Exporter settings API endpoints in the PHP API client.

Fixes: #147

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@faizan1191 could you please check the [failed pipeline](https://github.com/crowdin/crowdin-api-client-php/actions/runs/6372652381/job/17341303436?pr=153)? Thank you!

**Comment by faizan1191** [comment]
@andrii-bodnar sure i am checking it.

**Comment by faizan1191** [comment]
@andrii-bodnar just to acknowledge you I am on it and will fix this by today.

**Review by andrii-bodnar — APPROVED** [review]
@faizan1191 thank you!

**Comment by andrii-bodnar** [comment]
@faizan1191 some Unit tests have failed, could you please take a look?

**Comment by faizan1191** [comment]
@andrii-bodnar allow me sometime i will fix this by today

**Pull request merged**
